### ISSUE TITLE
use es6 arrow functions

### ISSUE THREAD

**Issue by mikenath223** [Luwat/rock-paper-scissors#3]
https://github.com/Luwat/rock-paper-scissors/blob/a119ddcd8b59a60df7cf9a3d7672dfe12da1a129/script/script.js#L14

Kindly change this and other regular functions to es6 arrow function syntax:
```
const playRound = (playerSelection, computerSelection) => {
}
```

**Comment by Luwat** [comment]
This issue has been addressed!

Thanks for your review and support @mikenath223.
